// cv-website/components/security/Guilloche.tsx
//
// Real engine-turned line work, generated by scripts/gen-guilloche.mjs into
// static SVGs and tinted here through mask-image. The curves are thousands of
// points long, so inlining them in JSX serialised the whole figure into the
// HTML once per instance; as masks they are fetched once and cached, and
// currentColor theming is replaced by a background the tokens still drive.

const ROSETTE = "url(/img/guilloche-rosette.svg)";
const RULE = "url(/img/lathe-rule.svg)";

const maskContain = {
  WebkitMaskImage: ROSETTE,
  maskImage: ROSETTE,
  WebkitMaskSize: "contain",
  maskSize: "contain",
  WebkitMaskRepeat: "no-repeat",
  maskRepeat: "no-repeat",
  WebkitMaskPosition: "center",
  maskPosition: "center",
} as const;

const maskStretch = {
  WebkitMaskImage: RULE,
  maskImage: RULE,
  WebkitMaskSize: "100% 100%",
  maskSize: "100% 100%",
  WebkitMaskRepeat: "no-repeat",
  maskRepeat: "no-repeat",
  WebkitMaskPosition: "center",
  maskPosition: "center",
} as const;

/** The closed figure a geometric lathe cuts. Colour comes from `background`,
 *  so callers tint with `bg-*` rather than `text-*`. */
export function GuillocheRosette({
  className = "",
  opacity,
}: {
  className?: string;
  /** Omit to let utility classes drive opacity (e.g. hover reveals). */
  opacity?: number;
}) {
  return (
    <div
      aria-hidden="true"
      className={className}
      style={opacity === undefined ? maskContain : { ...maskContain, opacity }}
    />
  );
}

/** The woven rule that separates fields of the record. */
export function LatheRule({
  className = "",
  style,
}: {
  className?: string;
  style?: React.CSSProperties;
}) {
  return (
    <div
      aria-hidden="true"
      className={className}
      style={{ ...maskStretch, ...style }}
    />
  );
}
